package me.ji5.realmtest.model;

import io.realm.RealmList;
import io.realm.RealmObject;

/**
 * A person infomation which is in the phonebook.
 *
 * @author ohjongin
 * @since 1.0
 * 14. 10. 7
 */
public class Contact extends RealmObject {
    private long conactId;
    private long dbId;
    private String displayName;
    private int photoId;
    private RealmList<Phone> phones;

    // Standard getters & setters generated by your IDE…
    public long getConactId() { return  conactId; }
    public void setConactId(long conactId) { this.conactId = conactId; }

    public long getDbId() { return dbId; }
    public void setDbId(long dbId) { this.dbId = dbId; }

    public String getDisplayName() { return displayName; }
    public void setDisplayName(String displayName) { this.displayName = displayName; }

    public int getPhotoId() { return photoId; }
    public void setPhotoId(int photoId) { this.photoId = photoId; }

    public RealmList<Phone> getPhones() { return phones; }
    public void setPhones(RealmList<Phone> phones) { this.phones = phones; }
}
